import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Products() {
  const [products, setProducts] = useState([])

  const getProducts = async () => {
    const resp = await fetch('http://localhost:3000/api/products')
    const data = await resp.json()
    setProducts(data.products)
  }

  useEffect(() => {
    getProducts()
  }, [])

  return (
    <>
      <Head>
        <title>Imagineshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cener}>
            <p>PRODUTOS EM PROMOÇÃO</p>
        </div>

        <div className={styles.grid}>
          {products.map(product => {
            return (
              <div 
                className={styles.card}
                key={product.id}
                >
                <h2 className={inter.className}>
                  {product.name}
                </h2>
                <p className={inter.className}>
                  {product.description}
                </p>
              </div>
            )
          })}
        </div>
      </main>
    </>
  )
}
