import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Products() {
  return (
    <>
      <Head>
        <title>Imagineshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cener}>
            <p>PRODUTOS EM PROMOÇÃO</p>
        </div>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2 className={inter.className}>
              Produto 1
            </h2>
            <p className={inter.className}>
              Descrição produto 1
            </p>
          </div>

          <div className={styles.card}>
            <h2 className={inter.className}>
              Produto 2
            </h2>
            <p className={inter.className}>
              Descrição produto 2
            </p>
          </div>

          <div className={styles.card}>
            <h2 className={inter.className}>
              Produto 3
            </h2>
            <p className={inter.className}>
              Descrição produto 3
            </p>
          </div>

          <div className={styles.card}>
            <h2 className={inter.className}>
              Produto 4
            </h2>
            <p className={inter.className}>
              Descrição produto 4
            </p>
          </div>
        </div>

        
      </main>
    </>
  )
}
