import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const resp = await fetch('http://localhost:3000/api/products')
  const data = await resp.json()

  return {
    revalidate: 10, // 10 segundos
    props: {
      products: data.products,
      randomNumber: data.randomNumber
    }
  }
}

const Products = props => {
  return (
    <>
      <Head>
        <title>Imagineshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cener}>
            <p>PRODUTOS EM PROMOÇÃO: {props.randomNumber}</p>
        </div>

        <div className={styles.grid}>
          {props.products.map(product => {
            return (
              <div 
                className={styles.card}
                key={product.id}
                >
                <h2 className={inter.className}>
                  {product.name}
                </h2>
                <p className={inter.className}>
                  {product.description}
                </p>
              </div>
            )
          })}
        </div>
      </main>
    </>
  )
}
export default Products;